config/routes.rb
Rails.application.routes.draw do
  resources :organizations
 
  devise_for :users, controllers: {sessions: 'users/sessions' , omniauth_callbacks: 'users/omniauth_callbacks'}
 
  resources :routes
  resources :vehicles
  resources :drivers
  root  :to => 'routes#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/route.rb
class Route < ApplicationRecord
 
  has_many :drivers, dependent: :destroy
  has_many :vehicles, dependent: :destroy
  has_many :organizations , dependent: :destroy

  accepts_nested_attributes_for :drivers 
  accepts_nested_attributes_for :vehicles 
  accepts_nested_attributes_for :organizations
 
  # validates :name, presence: true
  # validates :plate, presence: true
  validates_associated :drivers
  validates_associated :vehicles

  validates :start_at, :presence => true
  validates :ends_at, :presence => true
  validates :travel_time, :presence => true
  validates :total_stops, :presence => true 
  validates :status, :presence => true 
  

  enum status: [:llegada, :recogida]

  

 
  
  
  
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_route, only: %i[ show edit update destroy ]

  
  # GET /routes or /routes.json
  def index
    @routes = Route.all
  end

  # GET /routes/1 or /routes/1.json
  def show
  end

  # GET /routes/new
  def new
  
    @route = Route.new
    @route.drivers.new   
    @route.vehicles.new
    @route.organizations.new
    @driver = Driver.pluck :name, :id 
    @vehicle = Vehicle.pluck :plate, :id 
    @organization = Organization.pluck :name, :id 

    
  end

  # GET /routes/1/edit()
  def edit
    
  end

  # POST /routes or /routes.json
  def create
    @route = Route.new(route_params)

    respond_to do |format|
      if @route.save
        format.html { redirect_to route_url(@route), notice: "Route was successfully created." }
        format.json { render :show, status: :created, location: @route }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /routes/1 or /routes/1.json
  def update
    respond_to do |format|
      if @route.update(route_params)
        format.html { redirect_to route_url(@route), notice: "Route was successfully updated." }
        format.json { render :show, status: :ok, location: @route }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /routes/1 or /routes/1.json
  def destroy
    @route.destroy

    respond_to do |format|
      format.html { redirect_to routes_url, notice: "Route was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_route
      @route = Route.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def route_params
      params.require(:route).permit(:start_at, :ends_at, :travel_time, :total_stops, :status, :vehicle_id, :driver_id , drivers_attributes: [:name], vehicles_attributes: [:plate], organizations_attributes: [:name])
    end
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/views/routes/_form.html.erb
   
  <%= form_with(model: route) do |form| %>
    <% if route.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(route.errors.count, "error") %> prohibited this route from being saved:</h2>

        <ul>
          <% route.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

  

    <div class="form-group">
      <%= form.label :start_at %>
      <%= form.datetime_select :start_at %>
    </div>

    <div class="form-group">
      <%= form.label :ends_at %>
      <%= form.datetime_select :ends_at %>
    </div>

    <div class="form-group">
      <%= form.label :travel_time %>
      <%= form.time_select :travel_time %>
    </div>

    <div class="form-group">
      <%= form.label :total_stops %>
      <%= form.number_field :total_stops %>
    </div>

    <div class="form-group">
      <%= form.label :status %>
      <%= form.select :status, Route.statuses.keys, prompt: "seleciona una accion" %>  
      
    </div>
    
    <%= form.fields_for :organizations do |organization|%>
      <div class="form-group">
        <%= organization.select :name , Organization.where(id: [1,2]), class:"form-control"  %>
      </div>
    <%end%>

    
      <%= form.fields_for :drivers do |driver|%>
      <div class="form-group">
        <%= driver.select :name, Driver.where(id: [1,2,3,4,5]), class:"form-control" %>
      </div>
      <%end%>

      <%= form.fields_for :vehicles do |vehicle|%>
        <div class="form-group">
          <%= vehicle.select :plate ,Vehicle.where(id: [1,2,3,4,5,6,7,8]), class:"form-control" %>
        </div>
      <%end%>
    


    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

 

app/views/routes/edit.html.erb
<h1>Editing Route</h1>

<%= render 'form', route: @route %>

<%= link_to 'Show', @route %> |
<%= link_to 'Back', routes_path %>

app/views/routes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rutas</h1>


<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">organizacion</th>
      <th scope="col">Inicio Ruta</th>
      <th scope="col">Fin Ruta</th>
      <th scope="col">Tiempo de viaje</th>
      <th scope="col">Paradas</th>
      <th scope="col">Acción</th>
      <th scope="col">Conductor</th>
      <th scope="col">N° Vehicular</th>
    </tr>
  </thead>
  <tbody>
    <% @routes.each do |route| %>
    <tr>
      <td>
        <% route.organizations.each do |o| %>
          <%= o.name %>
        <% end%>
      </td>
      <td><%= route.start_at %></td>
      <td><%= route.ends_at %></td>
      <td><%= route.travel_time %></td>
      <td><%= route.total_stops %></td>
      <td><%= route.status %></td>
      <td>
      

        <% route.drivers.each do |d| %>
          <%= d.name %>
        <% end%>
      </td>
      <td>
        <% route.vehicles.each do |v| %>
          <%= v.plate %>
        <% end%>
      </td>

    
      <td><%= link_to 'Show', route %></td>
      <td><%= link_to 'Edit', edit_route_path(route) %></td>
      <td><%= button_to 'Destroy', route, method: :delete, data: { confirm: 'Are you sure?' } %></td>
     <% end%>
    </tr>
  </tbody>
</table>

<br>

<%= link_to 'New Route', new_route_path  %>

app/views/routes/new.html.erb
<div class="row">
  <div class="col-lg-4 col-md-6 ml-auto mr-auto">
    <h1>Crear nueva Ruta</h1>

    <%= render 'form', route: @route %>

    <%= link_to 'Back', routes_path %>
 </div>
</div>

app/views/routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start at:</strong>
  <%= @route.start_at %>
</p>

<p>
  <strong>Ends at:</strong>
  <%= @route.ends_at %>
</p>

<p>
  <strong>Travel time:</strong>
  <%= @route.travel_time %>
</p>

<p>
  <strong>Total stops:</strong>
  <%= @route.total_stops %>
</p>

<p>
  <strong>Action:</strong>
  <%= @route.status %>
</p>

<p>
  <strong>Dirver:</strong>
  <% @route.drivers.each do |d| %>
    <%= d.name %>
  <% end%>
</p>

<p>
  <strong>Vehicle:</strong>
   <% @route.vehicles.each do |v| %>
    <%= v.plate %>
  <% end%>
</p>

<%= link_to 'Edit', edit_route_path(@route) %> |
<%= link_to 'Back', routes_path %>